service: lambdagateway

provider:
  name: aws
  runtime: nodejs14.x
  role: ${opt:role}

functions:
  demo:
    handler: handler.demo
    events:
      - httpApi:
          path: /users/create
          method: get
