service: lambdagateway1

plugins:
  - serverless-plugin-datadog
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role: ${opt:aws_arn}

custom:
  datadog:
    forwarder: ${opt:dd_arn}
  webpack:
    includeModules: false

package:
  individually: true

functions:
  demo:
    handler: handlers/index.hello
