name: Deploy dev

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - run: npm i -g serverless
      - working-directory: ./sls_1
        run: sls remove --aws_arn ${{ secrets.SERVERLESS_ROLE }} --conceal
